### PR TITLE
Add Swift.package

### PR DESCRIPTION
**Pull request by piercifani**
This will allow this code to be consumed by SPM

### CODE REVIEW

**Comment by jsorge** [comment]
@piercifani Thanks for doing this! I'm running into a problem using your branch where using the resulting package doesn't work. When I run `swift build` on your changes I get the following error:
`no include directory found for target 'MarkdownAttributedString'; libraries cannot be imported without public headers`
Have you been able to work around the issue?

**Comment by piercifani** [comment]
Honestly I didn’t test from the command line, only the integration via Xcode, does that work?

**Comment by jsorge** [comment]
It's super inconsistent for me actually (I'm on the Xcode 12 beta at the moment). Sometimes the umbrella header will be generated and sometimes it won't. I'm really confused about what's going on.

**Comment by piercifani** [comment]
Closing since it's been too long...

**Pull request closed without merging**
